- name: Setup Dockerized Jenkins on EC2
  hosts: web
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Download Docker GPG key (pre-dearmored)
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'
      when: docker_check.rc != 0

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker
      when: docker_check.rc != 0

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
      when: docker_check.rc != 0

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Create Jenkins home directory
      file:
        path: /var/jenkins_home
        state: directory
        mode: '0755'

    - name: Fix permissions for Jenkins home
      command: chown -R 1000:1000 /var/jenkins_home

    - name: Run Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /var/jenkins_home:/var/jenkins_home
